export const enum mutate {
    SET_USER = 'SET_USER',
    SET_TOKEN = 'SET_TOKEN',
    SHOW_ERROR = 'SHOW_ERROR',
    SHOW_ALERT = 'SHOW_ALERT',
    HIDE_ALERT = 'HIDE_ALERT',
    INCREASE_ACTIVE_TAB = 'INCREASE_ACTIVE_TAB',
    DECREASE_ACTIVE_TAB = 'DECREASE_ACTIVE_TAB',

}